### PR TITLE
Add support for minute-level resolution

### PR DESCRIPTION
**Pull request by bibekg**
Before
image

After (with `props.hourlyChunks=2` and `props.timeFormat=h:mma`)
image

### CODE REVIEW

**Comment by yzalvov** [comment]
Hi @bibekg 
Thanks for the product. I'm going to utilise it. Please clarify what's the plan with this PR though? Thanks.

**Comment by bibekg** [comment]
Hi @yzalvov, sorry this took so long, I haven't had the time to maintain this project. Just published v1.0.4 which includes this PR's changes.

**Comment by bibekg** [comment]
Resolves #18

**Comment by yzalvov** [comment]
Hi @bibekg 
Thanks for the update and the feature. I will let you know if there is anything unexpected once the module is used.
🙏🏽

**Pull request merged**
